//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSM97Lib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSM97Lib.EnumResources", typeof(EnumResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PlayerAttribute_Acceleration {
            get {
                return ResourceManager.GetString("PlayerAttribute_Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PlayerAttribute_Agility {
            get {
                return ResourceManager.GetString("PlayerAttribute_Agility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PlayerAttribute_Awareness {
            get {
                return ResourceManager.GetString("PlayerAttribute_Awareness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PlayerAttribute_Consistency {
            get {
                return ResourceManager.GetString("PlayerAttribute_Consistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PlayerAttribute_Control {
            get {
                return ResourceManager.GetString("PlayerAttribute_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PlayerAttribute_Coolness {
            get {
                return ResourceManager.GetString("PlayerAttribute_Coolness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PlayerAttribute_Determination {
            get {
                return ResourceManager.GetString("PlayerAttribute_Determination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PlayerAttribute_Dribbling {
            get {
                return ResourceManager.GetString("PlayerAttribute_Dribbling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PlayerAttribute_Fitness {
            get {
                return ResourceManager.GetString("PlayerAttribute_Fitness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PlayerAttribute_Flair {
            get {
                return ResourceManager.GetString("PlayerAttribute_Flair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PlayerAttribute_Greed {
            get {
                return ResourceManager.GetString("PlayerAttribute_Greed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PlayerAttribute_Handling {
            get {
                return ResourceManager.GetString("PlayerAttribute_Handling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PlayerAttribute_Heading {
            get {
                return ResourceManager.GetString("PlayerAttribute_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PlayerAttribute_Kicking {
            get {
                return ResourceManager.GetString("PlayerAttribute_Kicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PlayerAttribute_Leadership {
            get {
                return ResourceManager.GetString("PlayerAttribute_Leadership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PlayerAttribute_Passing {
            get {
                return ResourceManager.GetString("PlayerAttribute_Passing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PlayerAttribute_Shooting {
            get {
                return ResourceManager.GetString("PlayerAttribute_Shooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PlayerAttribute_Speed {
            get {
                return ResourceManager.GetString("PlayerAttribute_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PlayerAttribute_Stamina {
            get {
                return ResourceManager.GetString("PlayerAttribute_Stamina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PlayerAttribute_Strength {
            get {
                return ResourceManager.GetString("PlayerAttribute_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PlayerAttribute_TackleDetermination {
            get {
                return ResourceManager.GetString("PlayerAttribute_TackleDetermination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PlayerAttribute_TackleSkill {
            get {
                return ResourceManager.GetString("PlayerAttribute_TackleSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PlayerAttribute_ThrowIn {
            get {
                return ResourceManager.GetString("PlayerAttribute_ThrowIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PlayerAttribute_Throwing {
            get {
                return ResourceManager.GetString("PlayerAttribute_Throwing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingActivityType_Control {
            get {
                return ResourceManager.GetString("TrainingActivityType_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingActivityType_Exercise {
            get {
                return ResourceManager.GetString("TrainingActivityType_Exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingActivityType_FiveASide {
            get {
                return ResourceManager.GetString("TrainingActivityType_FiveASide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingActivityType_GoalKeeping {
            get {
                return ResourceManager.GetString("TrainingActivityType_GoalKeeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingActivityType_Handling {
            get {
                return ResourceManager.GetString("TrainingActivityType_Handling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingActivityType_Heading {
            get {
                return ResourceManager.GetString("TrainingActivityType_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingActivityType_Jogging {
            get {
                return ResourceManager.GetString("TrainingActivityType_Jogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingActivityType_Kicking {
            get {
                return ResourceManager.GetString("TrainingActivityType_Kicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingActivityType_Marking {
            get {
                return ResourceManager.GetString("TrainingActivityType_Marking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingActivityType_None {
            get {
                return ResourceManager.GetString("TrainingActivityType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingActivityType_Passing {
            get {
                return ResourceManager.GetString("TrainingActivityType_Passing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingActivityType_Physiotherapist {
            get {
                return ResourceManager.GetString("TrainingActivityType_Physiotherapist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingActivityType_Shooting {
            get {
                return ResourceManager.GetString("TrainingActivityType_Shooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingActivityType_Sprinting {
            get {
                return ResourceManager.GetString("TrainingActivityType_Sprinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingActivityType_Tackling {
            get {
                return ResourceManager.GetString("TrainingActivityType_Tackling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingActivityType_Throwing {
            get {
                return ResourceManager.GetString("TrainingActivityType_Throwing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingActivityType_TrainingMatch {
            get {
                return ResourceManager.GetString("TrainingActivityType_TrainingMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingActivityType_WeightTraining {
            get {
                return ResourceManager.GetString("TrainingActivityType_WeightTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingActivityType_ZonalDefence {
            get {
                return ResourceManager.GetString("TrainingActivityType_ZonalDefence", resourceCulture);
            }
        }
    }
}
