//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSM97Lib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSM97Lib.EnumResources", typeof(EnumResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingScheduleType_Control {
            get {
                return ResourceManager.GetString("TrainingScheduleType_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingScheduleType_Exercise {
            get {
                return ResourceManager.GetString("TrainingScheduleType_Exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingScheduleType_FiveASide {
            get {
                return ResourceManager.GetString("TrainingScheduleType_FiveASide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingScheduleType_GoalKeeping {
            get {
                return ResourceManager.GetString("TrainingScheduleType_GoalKeeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingScheduleType_Handling {
            get {
                return ResourceManager.GetString("TrainingScheduleType_Handling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingScheduleType_Heading {
            get {
                return ResourceManager.GetString("TrainingScheduleType_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingScheduleType_Jogging {
            get {
                return ResourceManager.GetString("TrainingScheduleType_Jogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingScheduleType_Kicking {
            get {
                return ResourceManager.GetString("TrainingScheduleType_Kicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingScheduleType_Marking {
            get {
                return ResourceManager.GetString("TrainingScheduleType_Marking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingScheduleType_None {
            get {
                return ResourceManager.GetString("TrainingScheduleType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingScheduleType_Passing {
            get {
                return ResourceManager.GetString("TrainingScheduleType_Passing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingScheduleType_Physiotherapist {
            get {
                return ResourceManager.GetString("TrainingScheduleType_Physiotherapist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingScheduleType_Shooting {
            get {
                return ResourceManager.GetString("TrainingScheduleType_Shooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingScheduleType_Sprinting {
            get {
                return ResourceManager.GetString("TrainingScheduleType_Sprinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingScheduleType_Tackling {
            get {
                return ResourceManager.GetString("TrainingScheduleType_Tackling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingScheduleType_Throwing {
            get {
                return ResourceManager.GetString("TrainingScheduleType_Throwing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingScheduleType_TrainingMatch {
            get {
                return ResourceManager.GetString("TrainingScheduleType_TrainingMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingScheduleType_WeightTraining {
            get {
                return ResourceManager.GetString("TrainingScheduleType_WeightTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrainingScheduleType_ZonalDefence {
            get {
                return ResourceManager.GetString("TrainingScheduleType_ZonalDefence", resourceCulture);
            }
        }
    }
}
