//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSM97Patcher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSM97Patcher.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open file :{0}.
        /// </summary>
        internal static string CannotOpenFile {
            get {
                return ResourceManager.GetString("CannotOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Version.
        /// </summary>
        internal static string ChineseVersion {
            get {
                return ResourceManager.GetString("ChineseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English or global version.
        /// </summary>
        internal static string EnglishOrGlobalVersion {
            get {
                return ResourceManager.GetString("EnglishOrGlobalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original version.
        /// </summary>
        internal static string OriginalVersion {
            get {
                return ResourceManager.GetString("OriginalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patched version.
        /// </summary>
        internal static string PatchedVersion {
            get {
                return ResourceManager.GetString("PatchedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported game version, file size not recognizeable.
        /// </summary>
        internal static string UnsupportedGameversionFileSize {
            get {
                return ResourceManager.GetString("UnsupportedGameversionFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported game version, magic number 1 mismatch..
        /// </summary>
        internal static string UnsupportedGameVersionMagicNumber1Mismatch {
            get {
                return ResourceManager.GetString("UnsupportedGameVersionMagicNumber1Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported game version, magic number 2 mismatch..
        /// </summary>
        internal static string UnsupportedGameVersionMagicNumber2Mismatch {
            get {
                return ResourceManager.GetString("UnsupportedGameVersionMagicNumber2Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported patch version..
        /// </summary>
        internal static string UnsupportedPatchversion {
            get {
                return ResourceManager.GetString("UnsupportedPatchversion", resourceCulture);
            }
        }
    }
}
