//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fsm97Trainer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fsm97Trainer.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All player data boosted..
        /// </summary>
        internal static string AllPlayerDataBoosted {
            get {
                return ResourceManager.GetString("AllPlayerDataBoosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find game process!.
        /// </summary>
        internal static string CannotFindGameProcess {
            get {
                return ResourceManager.GetString("CannotFindGameProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find new spawn..
        /// </summary>
        internal static string CannotFindNewSpawn {
            get {
                return ResourceManager.GetString("CannotFindNewSpawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only change at season start..
        /// </summary>
        internal static string CanOnlyChangeAtSeasonStart {
            get {
                return ResourceManager.GetString("CanOnlyChangeAtSeasonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only change date in offseason..
        /// </summary>
        internal static string CanOnlyChangeDateInOffseason {
            get {
                return ResourceManager.GetString("CanOnlyChangeDateInOffseason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formation saved..
        /// </summary>
        internal static string FormationSaved {
            get {
                return ResourceManager.GetString("FormationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To avoid age bug after 2079 you should reset date before 2079. In addition, resetting date would disrupt game scheduling, you should only do it in offseason. Continue?.
        /// </summary>
        internal static string GameDateChangeWarning {
            get {
                return ResourceManager.GetString("GameDateChangeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an integer between 1901 and 2078..
        /// </summary>
        internal static string GameDateOutOfReangePrompt {
            get {
                return ResourceManager.GetString("GameDateOutOfReangePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game date eeset,.
        /// </summary>
        internal static string GameDateReset {
            get {
                return ResourceManager.GetString("GameDateReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving formation requires 11 players on the field, including a GK..
        /// </summary>
        internal static string InvalidFormationForSaving {
            get {
                return ResourceManager.GetString("InvalidFormationForSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land Purchased。.
        /// </summary>
        internal static string LandPurchased {
            get {
                return ResourceManager.GetString("LandPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one menus.exe process found..
        /// </summary>
        internal static string MultipleGameProcessFound {
            get {
                return ResourceManager.GetString("MultipleGameProcessFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Position to Formation requires 11 Players on the field.
        /// </summary>
        internal static string NotEnoughPlayersForAutoPosition {
            get {
                return ResourceManager.GetString("NotEnoughPlayersForAutoPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player data copied.
        /// </summary>
        internal static string PlayerDataCopied {
            get {
                return ResourceManager.GetString("PlayerDataCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player data imported..
        /// </summary>
        internal static string PlayerDataImported {
            get {
                return ResourceManager.GetString("PlayerDataImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player data pasted..
        /// </summary>
        internal static string PlayerDataPasted {
            get {
                return ResourceManager.GetString("PlayerDataPasted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player names updated.
        /// </summary>
        internal static string PlayerNamesUpdated {
            get {
                return ResourceManager.GetString("PlayerNamesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players rotated..
        /// </summary>
        internal static string PlayersRotated {
            get {
                return ResourceManager.GetString("PlayersRotated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please copy player data first.
        /// </summary>
        internal static string PleaseCopyPlayerDataFirst {
            get {
                return ResourceManager.GetString("PleaseCopyPlayerDataFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please switch to the training schedule page first. Continue?.
        /// </summary>
        internal static string PleaseSwitchToTheTrainingSchedulePageFirstContinue {
            get {
                return ResourceManager.GetString("PleaseSwitchToTheTrainingSchedulePageFirstContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position auto reset..
        /// </summary>
        internal static string PositionAutoReset {
            get {
                return ResourceManager.GetString("PositionAutoReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only be done at the beginning of the season, continue?.
        /// </summary>
        internal static string SeasonBeginningOnly {
            get {
                return ResourceManager.GetString("SeasonBeginningOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select player data export location.
        /// </summary>
        internal static string SelectPlayerDataExportLlocation {
            get {
                return ResourceManager.GetString("SelectPlayerDataExportLlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported game version..
        /// </summary>
        internal static string UnsupportedGameVersion {
            get {
                return ResourceManager.GetString("UnsupportedGameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing subs to GK will avoid training injories mostly but players will complain and sometimes threaten to retire, and managers will want you to increase performance (but you won&apos;t be fired). Continue?.
        /// </summary>
        internal static string WarningConvertToGK {
            get {
                return ResourceManager.GetString("WarningConvertToGK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youth player data boosted..
        /// </summary>
        internal static string YouthPlayerDataBoosted {
            get {
                return ResourceManager.GetString("YouthPlayerDataBoosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youth player not found..
        /// </summary>
        internal static string YouthPlayerNotFound {
            get {
                return ResourceManager.GetString("YouthPlayerNotFound", resourceCulture);
            }
        }
    }
}
