//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fsm97Trainer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fsm97Trainer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All player data boosted..
        /// </summary>
        internal static string AllPlayerDataBoosted {
            get {
                return ResourceManager.GetString("AllPlayerDataBoosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average weeks:{0}.
        /// </summary>
        internal static string AverageWeeks {
            get {
                return ResourceManager.GetString("AverageWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottleneck Attributes.
        /// </summary>
        internal static string BottleneckAttributes {
            get {
                return ResourceManager.GetString("BottleneckAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find game process!.
        /// </summary>
        internal static string CannotFindGameProcess {
            get {
                return ResourceManager.GetString("CannotFindGameProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find new spawn..
        /// </summary>
        internal static string CannotFindNewSpawn {
            get {
                return ResourceManager.GetString("CannotFindNewSpawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only change at season start..
        /// </summary>
        internal static string CanOnlyChangeAtSeasonStart {
            get {
                return ResourceManager.GetString("CanOnlyChangeAtSeasonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only change date in offseason..
        /// </summary>
        internal static string CanOnlyChangeDateInOffseason {
            get {
                return ResourceManager.GetString("CanOnlyChangeDateInOffseason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT ?item ?itemLabel_en ?birthDate WHERE {{
        ///  ?player a dbo:SoccerPlayer ;
        ///  rdfs:label ?itemLabel;
        ///  owl:sameAs ?item;
        ///  dbo:birthDate ?birthDate;
        ///dct:subject ?category.
        ///  FILTER (lang(?itemLabel) = &quot;en&quot;)
        ///FILTER(YEAR(?birthDate) = {0})       # born in 1987
        ///FILTER(STRSTARTS(STR(?item), &quot;http://www.wikidata.org/entity/Q&quot;))
        ///FILTER(STRSTARTS(STR(?category), &quot;http://dbpedia.org/resource/Category:{1}&quot;))
        ///# Extract QID string
        ///  BIND(STRAFTER(STR(?item), &quot;http://www.wikidata.org/entity/Q&quot;) AS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DbpediaGetPlayerByYearAndCategoryQuery {
            get {
                return ResourceManager.GetString("DbpediaGetPlayerByYearAndCategoryQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT ?item ?itemLabel_en ?birthDate WHERE {{
        ///  ?player a dbo:SoccerPlayer ;
        ///  rdfs:label ?itemLabel;
        ///  owl:sameAs ?item;
        ///  dbo:birthDate ?birthDate.
        ///  FILTER (lang(?itemLabel) = &quot;en&quot;)
        ///FILTER(YEAR(?birthDate) = {0})       # born in 1987
        ///FILTER(STRSTARTS(STR(?item), &quot;http://www.wikidata.org/entity/Q&quot;))
        ///# Extract QID string
        ///  BIND(STRAFTER(STR(?item), &quot;http://www.wikidata.org/entity/Q&quot;) AS ?qid)
        /// BIND(STR(?itemLabel) AS ?itemLabel_en)
        ///}}
        ///ORDER BY xsd:integer(?qid)
        ///LIMIT {1}.
        /// </summary>
        internal static string DBPediaGetPlayerByYearQuery {
            get {
                return ResourceManager.GetString("DBPediaGetPlayerByYearQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - {0,19}, {1,-24}    Age: {2,2}  Stats: {3}  Position: {4}   Nationality {5} weeks to max: {6}.
        /// </summary>
        internal static string EvalTopPlayerEntry {
            get {
                return ResourceManager.GetString("EvalTopPlayerEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top players for position {0}:.
        /// </summary>
        internal static string EvalTopPlayersHeader {
            get {
                return ResourceManager.GetString("EvalTopPlayersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluating player with positions {0}/{1}.
        /// </summary>
        internal static string EvaluatingPlayerPositionsProgressReport {
            get {
                return ResourceManager.GetString("EvaluatingPlayerPositionsProgressReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Complete.
        /// </summary>
        internal static string EvaluationCompleted {
            get {
                return ResourceManager.GetString("EvaluationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation in progress please wait..
        /// </summary>
        internal static string EvaluationInProgressPleaseWait {
            get {
                return ResourceManager.GetString("EvaluationInProgressPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read players for the moment, the game might be busy, try again later..
        /// </summary>
        internal static string FailedToReadPlayersForTheMoment {
            get {
                return ResourceManager.GetString("FailedToReadPlayersForTheMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formation saved..
        /// </summary>
        internal static string FormationSaved {
            get {
                return ResourceManager.GetString("FormationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Location.
        /// </summary>
        internal static string FormMainSaveToCsvDialogTitle {
            get {
                return ResourceManager.GetString("FormMainSaveToCsvDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To avoid age bug after 2079 you should reset date before 2079. In addition, resetting date would disrupt game scheduling, you should only do it in offseason. Continue?.
        /// </summary>
        internal static string GameDateChangeWarning {
            get {
                return ResourceManager.GetString("GameDateChangeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an integer between 1901 and 2078..
        /// </summary>
        internal static string GameDateOutOfReangePrompt {
            get {
                return ResourceManager.GetString("GameDateOutOfReangePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game date eeset,.
        /// </summary>
        internal static string GameDateReset {
            get {
                return ResourceManager.GetString("GameDateReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving formation requires 11 players on the field, including a GK..
        /// </summary>
        internal static string InvalidFormationForSaving {
            get {
                return ResourceManager.GetString("InvalidFormationForSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land Purchased。.
        /// </summary>
        internal static string LandPurchased {
            get {
                return ResourceManager.GetString("LandPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one menus.exe process found..
        /// </summary>
        internal static string MultipleGameProcessFound {
            get {
                return ResourceManager.GetString("MultipleGameProcessFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        internal static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Position to Formation requires 11 Players on the field.
        /// </summary>
        internal static string NotEnoughPlayersForAutoPosition {
            get {
                return ResourceManager.GetString("NotEnoughPlayersForAutoPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player data copied.
        /// </summary>
        internal static string PlayerDataCopied {
            get {
                return ResourceManager.GetString("PlayerDataCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player data imported..
        /// </summary>
        internal static string PlayerDataImported {
            get {
                return ResourceManager.GetString("PlayerDataImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player data pasted..
        /// </summary>
        internal static string PlayerDataPasted {
            get {
                return ResourceManager.GetString("PlayerDataPasted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player names updated.
        /// </summary>
        internal static string PlayerNamesUpdated {
            get {
                return ResourceManager.GetString("PlayerNamesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players rotated..
        /// </summary>
        internal static string PlayersRotated {
            get {
                return ResourceManager.GetString("PlayersRotated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please copy player data first.
        /// </summary>
        internal static string PleaseCopyPlayerDataFirst {
            get {
                return ResourceManager.GetString("PleaseCopyPlayerDataFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please switch to the training schedule page first. Continue?.
        /// </summary>
        internal static string PleaseSwitchToTheTrainingSchedulePageFirstContinue {
            get {
                return ResourceManager.GetString("PleaseSwitchToTheTrainingSchedulePageFirstContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position auto reset..
        /// </summary>
        internal static string PositionAutoReset {
            get {
                return ResourceManager.GetString("PositionAutoReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Rating.
        /// </summary>
        internal static string PositionRating {
            get {
                return ResourceManager.GetString("PositionRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only be done at the beginning of the season, continue?.
        /// </summary>
        internal static string SeasonBeginningOnly {
            get {
                return ResourceManager.GetString("SeasonBeginningOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select player data export location.
        /// </summary>
        internal static string SelectPlayerDataExportLlocation {
            get {
                return ResourceManager.GetString("SelectPlayerDataExportLlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total wekks:.
        /// </summary>
        internal static string TotalRoundsForEachTrainingScheduleType {
            get {
                return ResourceManager.GetString("TotalRoundsForEachTrainingScheduleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Schedule.
        /// </summary>
        internal static string TrainingSchedule {
            get {
                return ResourceManager.GetString("TrainingSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported game version..
        /// </summary>
        internal static string UnsupportedGameVersion {
            get {
                return ResourceManager.GetString("UnsupportedGameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing subs to GK will avoid training injories mostly but players will complain and sometimes threaten to retire, and managers will want you to increase performance (but you won&apos;t be fired). Continue?.
        /// </summary>
        internal static string WarningConvertToGK {
            get {
                return ResourceManager.GetString("WarningConvertToGK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeks.
        /// </summary>
        internal static string WeeksCount {
            get {
                return ResourceManager.GetString("WeeksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeks To Max.
        /// </summary>
        internal static string WeeksToMax {
            get {
                return ResourceManager.GetString("WeeksToMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  SELECT ?item  ?itemLabel_en ?itemLabel_zh ?birthDate WHERE {{
        /// ?item wdt:P31 wd:Q5;                # instance of human
        /// wdt:P106 wd:Q937857;          # occupation: association football player
        /// wdt:P569 ?birthDate.          # date of birth
        /// FILTER(YEAR(?birthDate) = {0})       # born in 1987
        /// SERVICE wikibase:label {{
        ///  bd:serviceParam wikibase:language &quot;en&quot;.
        ///  ?item rdfs:label ?itemLabel_en.
        /// }}
        /// SERVICE wikibase:label {{
        ///  bd:serviceParam wikibase:language &quot;zh&quot;.
        ///  ?item rdfs:label ?itemLabel_zh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WikiDataQueryGetPlayerNameByBirthYear {
            get {
                return ResourceManager.GetString("WikiDataQueryGetPlayerNameByBirthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ?item ?itemLabel_en ?itemLabel_zh ?birthDate
        /// WHERE {{
        ///  SERVICE wikibase:mwapi {{
        ///    bd:serviceParam wikibase:endpoint &quot;en.wikipedia.org&quot;;
        ///      wikibase:api &quot;Generator&quot;;
        ///      mwapi:generator &quot;categorymembers&quot;;
        ///      mwapi:gcmtitle &quot;Category:{0}&quot;;
        ///      mwapi:gcmprop &quot;ids&quot;;
        ///      mwapi:gcmlimit &quot;{1}&quot;.
        ///    ?item wikibase:apiOutputItem mwapi:item.
        ///  }}
        ///  ?item wdt:P569 ?birthDate
        ///  SERVICE wikibase:label {{
        ///    bd:serviceParam wikibase:language &quot;en&quot;.
        ///    ?item rdfs:label ?itemLabel_en. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WikiDataQueryGetPlayerNameByBirthYearWithinCategory {
            get {
                return ResourceManager.GetString("WikiDataQueryGetPlayerNameByBirthYearWithinCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youth player data boosted..
        /// </summary>
        internal static string YouthPlayerDataBoosted {
            get {
                return ResourceManager.GetString("YouthPlayerDataBoosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youth player not found..
        /// </summary>
        internal static string YouthPlayerNotFound {
            get {
                return ResourceManager.GetString("YouthPlayerNotFound", resourceCulture);
            }
        }
    }
}
